name = "ComplexVisual"
uuid = "2a97bfb4-3a20-40ee-9094-a7b6a37a937b"
authors = ["Christian Ludwig <ludwig@ma.tum.de>"]
version = "0.1.0"

[compat]
julia = "1.6"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComplexPortraits = "17699382-6153-4e65-8b03-b2dc23b1a9dc"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
